### PR TITLE
Fix the vanishing-phone problem

### LINKED ISSUE #235: [PE-D][Tester C] Phone number disappears after renaming a contact.
**Description:**
When renaming a contact, the phone number associated with the contact disappears and is no longer visible in the contact details.

**Steps to Reproduce:**
1. Add a contact with a name (e.g. "Jane") and a phone number (e.g. 123456).
2. Rename the contact to a new name
     `rename 8 n/John`
3. Press Enter.
4. Check the contact details again.

 **Expected Behaviour:**
The phone number should remain intact and visible after renaming the contact.

**Actual Behaviour:**
The phone number disappears and is no longer visible after renaming the contact.

**Screenshot:**
_Before_

_After_

**Suggested Improvement:**
Ensure that renaming a contact does not affect or remove any existing contact details, such as the phone number. The phone number should remain associated with the contact even after the name is changed.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jniaorx/ped#14

### PR DESCRIPTION
**Pull request by yuto1115**
Fix #235 

This problem was caused by some commands calling the old constructor of Loan, which does not take Phone as an argument and sets this.phone as the default value.

To ensure that there's no bugs left, I replaced all the usages of the old Loan constructor (including test codes) with the one that requires Phone, and deleted the old constructor.

Total lines of modified functional codes: 22

### CODE REVIEW

File: src/main/java/wanted/model/loan/Loan.java [hunk 1]
```diff
@@ -43,17 +43,6 @@ public Loan(Name name) {
         this.phone = Phone.EMPTY_PHONE;
     }
 
-    /**
-     * Constructs a new Loan object with the given name, LoanAmount, and tags.
-     */
-    public Loan(Name name, LoanAmount loanAmount, Set<Tag> tags) {
```
Comment (nikingoda) [inline src/main/java/wanted/model/loan/Loan.java:49]: Deleted the old constructors. LGTM!

File: src/test/java/wanted/testutil/PersonBuilder.java [hunk 2]
```diff
@@ -62,8 +66,16 @@ public PersonBuilder withAmount(LoanAmount loanAmount) {
         return this;
     }
 
+    /**
+     * Sets the {@code Phone} of the {@code Loan} that we are building.
```
Comment (nikingoda) [inline src/test/java/wanted/testutil/PersonBuilder.java:70]: LGTM!

**Review by nikingoda — COMMENTED** [review]
LGTM.
