### PR TITLE
Fix jsonproperty

### LINKED ISSUE #114: Inconsistency of JsonProperty name and actual key name
Small bug in JsonAdaptedLoan's constructor

_Originally posted by @sunpterodactyl in https://github.com/AY2425S2-CS2103T-F11-4/tp/pull/109#discussion_r2022161194_

### PR DESCRIPTION
**Pull request by yuto1115**
Fix #114

### CODE REVIEW

File: src/main/java/wanted/storage/JsonAdaptedLoan.java [hunk 1]
```diff
@@ -34,7 +34,7 @@ class JsonAdaptedLoan {
      */
     @JsonCreator
     public JsonAdaptedLoan(@JsonProperty("name") String name,
-                           @JsonProperty("amount") List<JsonAdaptedLoanTransaction> transactions,
+                           @JsonProperty("transactions") List<JsonAdaptedLoanTransaction> transactions,
```
Comment (sunpterodactyl) [inline src/main/java/wanted/storage/JsonAdaptedLoan.java:37]: lgtm

**Review by sunpterodactyl — COMMENTED** [review]
lgtm! will merge
