### PR TITLE
Fix storage and storage-related test issues

### LINKED ISSUE #95: Fix the bug of LoanBook storage
Since the LoanBook storage not yet matches our new Loan model, it does not store the loan book data correctly.

This can be fixed by implementing appropriate JSON counterpart of LoanAmount and integrating it into JSON LoanBook.

### PR DESCRIPTION
**Pull request by yuto1115**
Modified the `JsonAdaptedLoan` model so that the app can correctly save our new loan models.

Also fixed some issues of storage-related unit tests.

Fix #95

### CODE REVIEW

File: src/main/java/wanted/storage/JsonAdaptedLoan.java [hunk 1]
```diff
@@ -21,20 +22,24 @@
...
+    private final List<JsonAdaptedLoanTransaction> transactions = new ArrayList<>();
     private final List<JsonAdaptedTag> tags = new ArrayList<>();
 
     /**
      * Constructs a {@code JsonAdaptedLoan} with the given loan details.
      */
     @JsonCreator
     public JsonAdaptedLoan(@JsonProperty("name") String name,
-                           // @JsonProperty("amount") String amount,
+                           @JsonProperty("amount") List<JsonAdaptedLoanTransaction> transactions,
```
Comment (sunpterodactyl) [inline src/main/java/wanted/storage/JsonAdaptedLoan.java:37]: Labeled as "amount" but displayed as transactions?

**Review by sunpterodactyl — COMMENTED** [review]
just nits, lgtm overall!

File: src/main/java/wanted/storage/JsonAdaptedLoan.java (hunk 1 above)
Comment (yuto1115) [reply src/main/java/wanted/storage/JsonAdaptedLoan.java:37]: You're right! I will send another PR to fix it.

It's a bit weird that it works properly even with this bug...
