### PR TITLE
Standardise the format of command messages

### LINKED ISSUE #130: Format descriptions not consistent
The command format descriptions, which is displayed when we input commands in a wrong format, is written in an inconsistent way among commands. We should stick to the notations used in the user guide.

### PR DESCRIPTION
**Pull request by yuto1115**
**Please merge #153 first before merging this.**

Modified the MESSAGE_USAGE of all commands so that:

- the formats are standardised
- the notation used are consistent with UG

Fix #130

### CODE REVIEW

File: src/main/java/wanted/logic/commands/DelhistCommand.java [hunk 1]
```diff
@@ -14,18 +14,19 @@
...
 
     public static final String MESSAGE_USAGE = COMMAND_WORD
-            + ": Deletes a transaction in the history of the loan "
-            + "identified by the index number used in the displayed loan list.\n"
-            + "The deleted transaction is identified by the index number used in the history of the identified loan.\n"
-            + "Parameters: LOAN_ID "
-            + PREFIX_INDEX + "[TRANSACTION_ID] (both must be positive integers)\n"
+            + ": Deletes a transaction in the history of the person "
+            + "identified by the index number used in the displayed persons list.\n"
+            + "The deleted transaction is identified by the index number used in the history of the identified person.\n"
```
Comment (changjy81) [inline src/main/java/wanted/logic/commands/DelhistCommand.java:26]: This line is one character too long and failing checkstyle...

File: src/main/java/wanted/logic/commands/TagCommand.java [hunk 2]
```diff
@@ -1,6 +1,7 @@
 package wanted.logic.commands;
 
 import static java.util.Objects.requireNonNull;
+import static wanted.logic.parser.CliSyntax.PREFIX_NAME;
```
Comment (changjy81) [inline src/main/java/wanted/logic/commands/TagCommand.java:4]: Unused import failing checkstyle

**Review by changjy81 — CHANGES_REQUESTED** [review]
Please fix ASAP; the new command descriptions seem good otherwise.

**Review by changjy81 — APPROVED** [review]
Checkstyle errors fixed. Thank you for the quick response!
